import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { RoastResponse, RoastIssue } from "./api.js";

/**
 * Save a Full Truth review as a markdown report in the current directory.
 * Returns the file path if saved, null if skipped/failed.
 */
export function saveReport(response: RoastResponse, source: string): string | null {
  try {
    const { data, voice, meta } = response;
    const date = new Date().toISOString().split("T")[0];
    const filename = `sally-review-${date}.md`;
    const filepath = join(process.cwd(), filename);

    const lines: string[] = [];

    // Header
    lines.push(`# Sally's ${meta.mode === "full_truth" ? "Full Truth" : "Quick Roast"} Review`);
    lines.push("");
    lines.push(`**Date:** ${date}`);
    lines.push(`**Source:** ${source}`);
    lines.push(`**Files reviewed:** ${meta.files_reviewed}`);
    lines.push(`**Score:** ${data.score.toFixed(1)}/10`);
    lines.push("");
    lines.push("---");
    lines.push("");

    // Sally's verdict
    lines.push("## Sally's Verdict");
    lines.push("");
    const paragraphs = voice.roast.split("\n\n");
    for (const p of paragraphs) {
      lines.push(p);
      lines.push("");
    }

    // Top issues
    if (data.issues && data.issues.length > 0) {
      lines.push("---");
      lines.push("");
      lines.push("## Top Issues");
      lines.push("");

      for (let i = 0; i < data.issues.length; i++) {
        const issue = data.issues[i] as RoastIssue;
        const severity = issue.severity.toUpperCase();
        lines.push(`### ${i + 1}. \`${issue.issue_code}\` — ${severity}`);
        lines.push("");
        lines.push(`**${issue.title}**`);
        lines.push("");
        lines.push(issue.description);
        lines.push("");

        if (issue.evidence && issue.evidence.length > 0) {
          for (const e of issue.evidence) {
            lines.push(`- → ${e}`);
          }
          lines.push("");
        }

        if (issue.fix) {
          lines.push(`**Fix:** ${issue.fix}`);
          lines.push("");
        }
      }
    }

    // Actionable fixes
    if (data.actionable_fixes && data.actionable_fixes.length > 0) {
      lines.push("---");
      lines.push("");
      lines.push("## Actionable Fixes");
      lines.push("");
      for (const fix of data.actionable_fixes) {
        lines.push(`- ✓ ${fix}`);
      }
      lines.push("");
    }

    // Bright side + sneer
    lines.push("---");
    lines.push("");
    if (voice.bright_side) {
      lines.push(`> ✨ ${voice.bright_side}`);
      lines.push("");
    }
    if (voice.hardest_sneer) {
      lines.push(`> 🔥 ${voice.hardest_sneer}`);
      lines.push("");
    }

    // Footer
    lines.push("---");
    lines.push("");
    lines.push("*Generated by [Cynical Sally](https://cynicalsally.com) — brutally honest code reviews.*");
    lines.push("");

    writeFileSync(filepath, lines.join("\n"), "utf-8");
    return filepath;
  } catch {
    return null;
  }
}
